name       : lame
version    : '3.100'
release    : 10
source     :
    - https://netcologne.dl.sourceforge.net/project/lame/lame/3.100/lame-3.100.tar.gz : ddfe36cab873794038ae2c1210557ad34857a4b6bdc515785d1da9e175b1da1e
license    : LGPL-2.0-or-later
homepage   : https://lame.sourceforge.io/
summary    : High quality MPEG Audio Layer III (MP3) encoder.
component  : multimedia.codecs
description: |
    LAME is a high quality MPEG Audio Layer III (MP3) encoder.
optimize   : speed
builddeps  :
    - pkgconfig(ncursesw)
    - nasm
patterns   :
    - docs :
        - /usr/share/doc
setup      : |
    %configure --disable-static --enable-nasm --enable-expopt=full
build      : |
    %make V=1
install    : |
    %make_install
check      : |
    %make test
