name       : lame
version    : 3.99.5
release    : 6
source     :
    - http://downloads.sourceforge.net/lame/lame-3.99.5.tar.gz : 24346b4158e4af3bd9f2e194bb23eb473c75fb7377011523353196b19b9a23ff
license    : GPL-2.0
summary    : LAME is a high quality MPEG Audio Layer III (MP3) encoder.
component  : multimedia.codecs
description: |
    LAME is a high quality MPEG Audio Layer III (MP3) encoder.
optimize   : speed
builddeps  :
    - nasm
patterns   :
    - docs:
        - /usr/share/doc
setup      : |
    %patch -p1 < $pkgfiles/security/CVE-2017-8419.patch
    %configure --disable-static --enable-nasm --enable-expopt=full
build      : |
    %make V=1
install    : |
    %make_install
