name       : lame
version    : 3.99.5
release    : 3
source     :
    - http://downloads.sourceforge.net/lame/lame-3.99.5.tar.gz : 24346b4158e4af3bd9f2e194bb23eb473c75fb7377011523353196b19b9a23ff
license    : GPL-2.0
summary    : LAME is a high quality MPEG Audio Layer III (MP3) encoder.
description: |
    LAME is a high quality MPEG Audio Layer III (MP3) encoder.
builddeps  :
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
